#pragma once

#define MASTER_LEFT

#define USE_SERIAL_PD2

#define PERMISSIVE_HOLD
#define TAPPING_TERM 200

#define MOUSEKEY_DELAY 100
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_TIME_TO_MAX 70
#define MOUSEKEY_MAX_SPEED 10

#define MOUSEKEY_WHEEL_DELAY 300
#define MOUSEKEY_WHEEL_INTERVAL 100
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40
#define MOUSEKEY_WHEEL_MAX_SPEED 5


#define OLED_BRIGHTNESS 128

#define OLED_FONT_H "keyboards/crkbd/keymaps/gotham/glcdfont.c"
