#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#include "../../config.h"

#define NO_ACTION_ONESHOT
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

#define PERMISSIVE_HOLD
#define TAPPING_TERM 200

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7

#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_TIME_TO_MAX 255
#define MOUSEKEY_WHEEL_MAX_SPEED 0

#endif
